### ISSUE TITLE
connectivity test: cilium connectivity test should run pods that use ping with CAP_NET_RAW

### ISSUE THREAD

**Issue by asteven** [cilium/cilium-cli#270] opened 2021-06-02 13:48 UTC
The crio runtime has dropped CAP_NET_RAW from default capabilities since version 1.18.

This causes the 9 of 43 of ciliums connectivity tests to fail.

Changing crio's default_capabilities from:

```
default_capabilities = [
  "CHOWN",
  "DAC_OVERRIDE",
  "FSETID",
  "FOWNER",
  "SETGID",
  "SETUID",
  "SETPCAP",
  "NET_BIND_SERVICE",
  "KILL",
]
```

to:

```
default_capabilities = [
  "CHOWN",
  "DAC_OVERRIDE",
  "FSETID",
  "FOWNER",
  "SETGID",
  "SETUID",
  "SETPCAP",
  "NET_BIND_SERVICE",
  "KILL",
  "NET_RAW",
]
```

allows the cilium tests to run successfully.

The proper solution would be to run the pods that want to use ping with an explicitly configured CAP_NET_RAW.

**Comment by pchaigno** [comment] 2021-06-02 13:58
Duplicate of https://github.com/cilium/cilium-cli/issues/133.

**Closed by pchaigno** 2021-06-02 13:58 UTC
