### ISSUE TITLE
For consistency, expect cilium install to be executed multiple times

### ISSUE THREAD

**Issue by xiaods** [cilium/cilium-cli#754] opened 2022-03-11 08:52 UTC
## Proposal / RFE

**Is your feature request related to a problem?**

my kubernetes project k8e(getk8e.com) is dependcies for cilium as network cni. with install.sh, we use cilium install to install network. i found the install only run once.

**Describe the solution you'd like**

current behavior:
```bash
[ec2-user@ip-172-31-22-111 ~]$ cilium install
ℹ️  using Cilium version "v1.10.5"
🔮 Auto-detected cluster name: default
🔮 Auto-detected IPAM mode: cluster-pool
🔑 Found existing CA in secret cilium-ca
🔑 Generating certificates for Hubble...
↩️ Rolling back installation...

Error: Unable to install Cilium: unable to create secret kube-system/hubble-server-certs: secrets "hubble-server-certs" already exists

[ec2-user@ip-172-31-22-111 ~]$ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         OK
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 1, Ready: 1/1, Available: 1/1
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium-operator    Running: 1
                  cilium             Running: 1
Cluster Pods:     3/3 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.10.5: 1
                  cilium-operator    quay.io/cilium/operator-generic:v1.10.5: 1
```

just like upgrade.
```bash
[ec2-user@ip-172-31-22-111 ~]$ cilium upgrade
✅ cilium-operator is already up to date
✅ Cilium is already up to date
```

**Comment by tklauser** [comment] 2022-03-11 12:45
Thanks for the report @xiaods. Looks like the reported issue is a possible duplicate of #589. Are you seeing the behavior on interrupted installations or also when the first `cilium install` run suceeded?

**Comment by xiaods** [comment] 2022-03-12 09:00
@tklauser my context is my install script as install kubernetes one-step script.  some time the script is interrupted and need reinstall the step. i don't sure the cilium status is ok, the script will install again, then the cilium will report 
```
Error: Unable to install Cilium: unable to create secret kube-system/hubble-server-certs: secrets "hubble-server-certs" already exists
```
So, I  hope the cilium cli add  double check status step before install next step.

**Comment by xiaods** [comment] 2022-03-12 09:32
duplicate of https://github.com/cilium/cilium-cli/issues/589.

**Closed** 2022-03-12 09:32 UTC
Labels: kind/feature, kind/community-report
