### ISSUE TITLE
flake: External Workloads

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#329] opened 2021-06-17 05:29 UTC
# flake instances:

- https://github.com/cilium/cilium-cli/runs/2845728154?check_suite_focus=true
- https://github.com/cilium/cilium-cli/pull/319/checks?check_run_id=2899270560
- https://github.com/cilium/cilium-cli/pull/379/checks?check_run_id=2936147278

# symptom:

cilium fails to start:
```
Waiting for Cilium daemon to come up...
Waiting for Cilium daemon to come up...
Cilium status:
Get "http:///var/run/cilium/cilium.sock/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?
Timeout waiting for Cilium to start, retries exhausted.
```

# other notes

not sure if this is relevant, but i see this error in https://github.com/cilium/cilium-cli/runs/2845728154?check_suite_focus=true
```
2021-06-17T05:14:35.9974127Z 2021-06-17T05:13:28.711379090Z level=error msg="Command execution failed" cmd="[iptables -t mangle -n -L CILIUM_PRE_mangle]" error="exit status 1" subsys=iptables
```

**Comment by nbusseneau** [comment] 2021-06-17 11:21
We added agent restart retries in #290 but seems like this is a genuine failure with something else, not the agent booting up.

**Comment by michi-covalent** [comment] 2021-06-23 22:35
warning / error messages from https://github.com/cilium/cilium-cli/pull/319/checks?check_run_id=2899270560
```
2021-06-23T21:24:35.7510813Z 2021-06-23T21:23:25.693264603Z level=error msg="Command execution failed" cmd="[iptables -t mangle -n -L CILIUM_PRE_mangle]" error="exit status 1" subsys=iptables
2021-06-23T21:24:35.7512523Z 2021-06-23T21:23:25.693319502Z level=warning msg="# Warning: iptables-legacy tables present, use iptables-legacy to see them" subsys=iptables
2021-06-23T21:24:35.7514172Z 2021-06-23T21:23:25.693332978Z level=warning msg="iptables: No chain/target/match by that name." subsys=iptables
2021-06-23T21:24:35.7561715Z 2021-06-23T21:23:45.710192121Z ***"level":"warn","ts":"2021-06-23T21:23:45.709Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://clustermesh-apiserver.cilium.io:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 10.168.15.211:2379: connect: connection refused\""***
2021-06-23T21:24:35.7908462Z 2021-06-23T21:24:10.710701511Z ***"level":"warn","ts":"2021-06-23T21:24:10.710Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://clustermesh-apiserver.cilium.io:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 10.168.15.211:2379: connect: connection refused\""***
```

**Comment by nebril** [comment] 2021-06-24 14:55
Cilium not being able to connect to clustermesh apiserver is caused by pod in pending state:
```
kube-system   clustermesh-apiserver-78866fc77b-zmgpx                           0/2     Pending     0          6m58s   <none>        <none>                                                <none>           <none>
```

**Comment by jrajahalme** [comment] 2021-07-01 19:26
https://github.com/cilium/cilium-cli/pull/353 may fix this as it will actually wait for the service backend to be available when doing `cilium clustermesh status --wait`. This was merged a week ago.

**Comment by tklauser** [comment] 2021-09-08 12:19
It looks like this flake hasn't been observed since #353 was merged. Thus closing this issue. Please comment/reopen in case you encounter the flake again.

**Closed by tklauser** 2021-09-08 12:19 UTC
Labels: area/CI
