### ISSUE TITLE
uninstall restarts cilium pod(s) after removing hubble

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium-cli#255] opened 2021-05-28 02:02 UTC
uninstall restarts cilium pod(s) after removing hubble (even when hubble was not enabled):
```
$ cilium uninstall
🔥 Deleting Hubble UI...
🔥 Deleting Relay...
🔥 Deleting Relay certificates...
♻️  Restarted Cilium pods
🔮 Auto-detected Kubernetes kind: kind
🔥 Deleting cilium-test namespace...
🔥 Deleting Service accounts...
🔥 Deleting ConfigMap...
🔥 Deleting Cluster roles...
🔥 Deleting agent DaemonSet...
🔥 Deleting operator Deployment...
🔥 Deleting clustermesh-apiserver...
🔥 Deleting ClusterMesh certificates...
🔥 Deleting certificates...
```

**Comment by jrajahalme** [comment] 2021-05-28 02:19
This may also only be a UI issue as on a 2nd try I don't see the cilium pod initializing after `cilium uninstall`. Possibly was issuing `cilium uninstall` before prior `cilium install` had fully completed.

**Comment by pchaigno** [comment] 2021-05-28 07:20
I think this is a duplicate of https://github.com/cilium/cilium-cli/issues/165.

**Comment by michi-covalent** [comment] 2022-10-06 23:32
this might be causing some issues in cilium CI. for example:

https://github.com/cilium/cilium/actions/runs/3189785349/jobs/5204016540#step:25:36

`cilium uninstall` gets stuck at `Waiting for cilium-test namespace to be terminated...`. looking at sysdump, `cilium-test` namespace is stuck in terminating state with this status:

```
      message: 'Discovery failed for some groups, 1 failing: unable to retrieve the
        complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently
        unable to handle the request'
      reason: DiscoveryFailed
```
i'm not 100% sure if cilium restart is causing this, but either way it doesn't make sense for `uninstall` to restart cilium.

**Closed** 2022-10-11 16:56 UTC
Labels: kind/bug, good first issue, help wanted
